version: '3.6'
services:
  dbs:
    image: mysql:8.0.26
    container_name: dbs
    environment:
      - MYSQL_ROOT_PASSWORD=root
    restart: always
    ports:
      - 3389:3306
    volumes:
      - ./db/cf/my.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./db/mysql:/var/lib/mysql

  node:
    image: node:21.7
    container_name: node
    user: "node"
    working_dir: /usr/node/app
    environment:
      - TZ=Asia/Bangkok
      - EXPRESS_HTTPS=true
      - EXPRESS_KEY=./cert/oja_key.pem
      - EXPRESS_CERT=./cert/oja_cert.pem
    restart: always
    volumes:
      - ./:/usr/node/app
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - dbs
    command: bash -c "npm install && npm run build && npm start"
