import { KnModel } from '../models/AssureAlias';
import { SurveyOperateHandler } from './SurveyOperateHandler';

export class MeasureEHandler extends SurveyOperateHandler {
    public readonly form_id : string = "MEASURE_E";
    public model : KnModel = {
        name: "measure_e",
        fields: {
            survey_id: { type: "STRING", key: true, created: true, updated: true  },
            profile_id: { type: "STRING", created: true },
            ME_1_1: { type: "STRING", created: true, updated: true  },
            ME_1_2: { type: "STRING", created: true, updated: true  },
            ME_1_3: { type: "STRING", created: true, updated: true  },
            ME_1_4: { type: "STRING", created: true, updated: true  },
            ME_1_5: { type: "STRING", created: true, updated: true  },
            ME_1_6: { type: "STRING", created: true, updated: true  },
            ME_2_1: { type: "STRING", created: true, updated: true  },
            ME_2_2: { type: "STRING", created: true, updated: true  },
            ME_2_3: { type: "STRING", created: true, updated: true  },
            ME_2_4: { type: "STRING", created: true, updated: true  },
            ME_2_5: { type: "STRING", created: true, updated: true  },
            ME_2_6: { type: "STRING", created: true, updated: true  },
            ME_2_7: { type: "STRING", created: true, updated: true  },
            ME_2_8: { type: "STRING", created: true, updated: true  },
            ME_2_9: { type: "STRING", created: true, updated: true  },
            ME_2_10: { type: "STRING", created: true, updated: true  },
            ME_2_11: { type: "STRING", created: true, updated: true  },
            ME_2_12: { type: "STRING", created: true, updated: true  },
            ME_2_13: { type: "STRING", created: true, updated: true  },
            ME_2_14: { type: "STRING", created: true, updated: true  },
            ME_2_15: { type: "STRING", created: true, updated: true  },
            ME_2_16: { type: "STRING", created: true, updated: true  },
            ME_2_17: { type: "STRING", created: true, updated: true  },
            ME_2_18: { type: "STRING", created: true, updated: true  },
            ME_2_19: { type: "STRING", created: true, updated: true  },
            ME_2_19_text: { type: "STRING", created: true, updated: true  },
            ME_3_1: { type: "STRING", created: true, updated: true  },
            ME_3_2: { type: "STRING", created: true, updated: true  },
            ME_3_3: { type: "STRING", created: true, updated: true  },
            ME_3_4: { type: "STRING", created: true, updated: true  },
            ME_3_5: { type: "STRING", created: true, updated: true  },
            ME_3_6: { type: "STRING", created: true, updated: true  },
            ME_3_7: { type: "STRING", created: true, updated: true  },
            ME_3_8: { type: "STRING", created: true, updated: true  },
            ME_3_9: { type: "STRING", created: true, updated: true  },
            ME_3_10: { type: "STRING", created: true, updated: true  },
            ME_3_11: { type: "STRING", created: true, updated: true  },
            ME_3_12: { type: "STRING", created: true, updated: true  },
            ME_3_13: { type: "STRING", created: true, updated: true  },
            ME_3_14: { type: "STRING", created: true, updated: true  },
            ME_3_15: { type: "STRING", created: true, updated: true  },
            ME_3_16: { type: "STRING", created: true, updated: true  },
            ME_3_17: { type: "STRING", created: true, updated: true  },
            ME_3_18: { type: "STRING", created: true, updated: true  },
            ME_3_19: { type: "STRING", created: true, updated: true  },
            ME_3_19_text: { type: "STRING", created: true, updated: true  },
            ME_3_20: { type: "STRING", created: true, updated: true  },
            ME_3_21: { type: "STRING", created: true, updated: true  },
            ME_3_22: { type: "STRING", created: true, updated: true  },
            ME_3_23: { type: "STRING", created: true, updated: true  },
            ME_3_24: { type: "STRING", created: true, updated: true  },
            ME_3_25: { type: "STRING", created: true, updated: true  },
            ME_3_26: { type: "STRING", created: true, updated: true  },
            ME_3_27: { type: "STRING", created: true, updated: true  },
            ME_3_28: { type: "STRING", created: true, updated: true  },
            ME_3_29: { type: "STRING", created: true, updated: true  },
            ME_3_30: { type: "STRING", created: true, updated: true  },
            ME_3_30_text: { type: "STRING", created: true, updated: true  },
            ME_4_1: { type: "STRING", created: true, updated: true  },
            ME_4_2: { type: "STRING", created: true, updated: true  },
            create_date: { type: "DATE", created: true, updated: false  },
            create_time: { type: "TIME", created: true, updated: false  },
            create_millis: { type: "BIGINT", created: true, updated: false  },
            create_by: { type: "STRING", created: true, updated: false  },
            update_date: { type: "DATE", created: true, updated: true  },
            update_time: { type: "TIME", created: true, updated: true  },
            update_millis: { type: "BIGINT", created: true, updated: true  },
            update_by: { type: "STRING", created: true, updated: true  }
        }
    };

}
